version: "3"
services:
    mongo:
      container_name: DATABASE
      image: mongo
      volumes:
            - db-data:/data/db
      ports:
            - "27017:27017"
      networks:
            - backend
    nodeapp:
      image: node:9
      container_name: API
      restart: always
      build: .
      ports:
            - "8080:3000"
      environment:
          - MONGODB_HOST=mongo
      networks:
          - backend

volumes:
      db-data:
networks:
      backend:
